language: cpp
compiler:
  - gcc
  - clang
before_install:
# Required Dependencies:
  - sudo apt-get install libboost-dev
before_script:
  - mkdir build && cd build && cmake -DVERBOSE=on ..
script:
  - make -j4
  - sudo make install
  - sudo make uninstall
  - make package
  - make clean
# whitelist
branches:
  only:
    - master
